name: my-app-secrets.

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env:
  AWS_REGION: "us-east-1"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.29.0'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::851725282145:role/github-snreddyboggu  # Add your IAM role ARN here
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up EKS kubeconfig
        run: aws eks update-kubeconfig --name test --region ${{ env.AWS_REGION }}

      - name: Debug kubeconfig
        run: |
          kubectl config view
          kubectl get nodes

      - name: Retrieve secrets
        id: fetch-secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: "my-app-secrets"  # Update this to your secret's name
          parse-json-secrets: false  # Set to true if the secret is in JSON format

      - name: Create Kubernetes secret
        run: |
          echo "${{ steps.fetch-secrets.outputs['my-app-secrets'] }}" | kubectl create secret generic my-app-secrets \
            --from-env-file=/dev/stdin \
            --dry-run=client -o yaml | kubectl apply -f -
