name: Retrieve and Store Secrets in Kubernetes

on:
  push:
    branches:
      - main

env:
  AWS_REGION: "us-east-1"

permissions:
  id-token: write   # Required for AWS OIDC
  contents: read    # Required for actions/checkout

jobs:
  manage-secrets:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::851725282145:role/github-snreddyboggu
          aws-region: ${{ env.AWS_REGION }}

      # Step 2: Retrieve secrets from AWS Secrets Manager
      - name: Retrieve secrets
        id: fetch-secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: my-app-secrets
          parse-json-secrets: false

      # Step 3: Debug - Output fetched secrets for testing (Remove after verification)
      - name: Debug Secrets Retrieval
        run: echo "${{ steps.fetch-secrets.outputs.my-app-secrets }}"

      # Step 4: Create Kubernetes secret (securely)
      - name: Create Kubernetes secret
        run: |
          echo "${{ steps.fetch-secrets.outputs.my-app-secrets }}" | kubectl create secret generic my-app-secrets \
            --from-env-file=/dev/stdin \
            --dry-run=client -o yaml | kubectl apply -f -
